/**
 * Embeds a tool's built single-file app (dist/mcp-app.html) into a TypeScript
 * module so the MCP server needs no filesystem access at runtime.
 * Usage: node scripts/embed-html.mjs <tool-name>
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const tool = process.argv[2];
if (!tool) {
  console.error("Usage: node scripts/embed-html.mjs <tool-name>");
  process.exit(1);
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// vite-plugin-singlefile emits to dist/<input path>.html
const built = path.join(root, "dist", "tools", tool, "mcp-app.html");
const html = await fs.readFile(built, "utf-8");
const out =
  "// GENERATED by scripts/embed-html.mjs. Do not edit. Run `npm run build` to refresh.\n" +
  `export const APP_HTML: string = ${JSON.stringify(html)};\n`;
const target = path.join(root, "tools", tool, "app-html.generated.ts");
await fs.writeFile(target, out);
console.log(`Embedded ${built} (${html.length} bytes) into ${target}`);
